apiVersion: v1
data:
  key1: config1
  key2: config2
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: config
  namespace: default
  annotations:
    argocd.argoproj.io/sync-options: Prune=confirm
